# Generated by Django 5.2.11 on 2026-03-01 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_historicaluserscustomerprofile_genser_and_more'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendorsstall',
            options={'managed': True},
        ),
        migrations.CreateModel(
            name='VendorActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('stall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendors.vendorsstall')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='users.usersvendorprofile')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
