# Generated by Django 5.2.11 on 2026-03-05 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendoractivitylog',
            name='changes',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
