# Generated by Django 5.2.11 on 2026-03-06 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('vendors', '0002_vendoractivitylog_changes'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendoractivitylog',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productscategory'),
        ),
        migrations.AddField(
            model_name='vendoractivitylog',
            name='food_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productsfooditem'),
        ),
    ]
