# Generated by Django 5.2.11 on 2026-03-19 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_ordersorder_rider'),
        ('vendors', '0003_vendoractivitylog_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendoractivitylog',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.ordersorder'),
        ),
    ]
