# Generated by Django 5.2.11 on 2026-03-06 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productsfooditem_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsfooditem',
            name='promo_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productsfooditem',
            name='promo_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
