# Generated by Django 5.2.11 on 2026-03-06 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productsfooditem_promo_end_and_more'),
        ('users', '0007_historicaluserscustomerprofile_genser_and_more'),
        ('vendors', '0003_vendoractivitylog_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='users.userscustomerprofile')),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='products.productsfooditem')),
                ('stall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='vendors.vendorsstall')),
            ],
            options={
                'db_table': 'products_cartitem',
                'ordering': ['-added_at'],
                'unique_together': {('customer', 'stall', 'food_item')},
            },
        ),
    ]
