# Generated by Django 5.2.11 on 2026-03-09 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_cartitem_is_selected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='is_selected',
        ),
    ]
