# Generated by Django 5.2.11 on 2026-03-23 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationsnotification',
            options={'managed': True, 'ordering': ['-created_at']},
        ),
    ]
