# Generated by Django 5.2.11 on 2026-03-23 08:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notificationsnotification_options'),
        ('orders', '0004_ordersorder_rider'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsnotification',
            name='notification_type',
            field=models.CharField(blank=True, choices=[('order_placed', 'Order Placed'), ('order_confirmed', 'Order Confirmed'), ('order_preparing', 'Order Preparing'), ('order_ready', 'Order Ready'), ('order_picked_up', 'Order Picked Up'), ('order_out_for_delivery', 'Order Out for Delivery'), ('order_completed', 'Order Completed'), ('order_cancelled', 'Order Cancelled'), ('account_approved', 'Account Approved'), ('account_rejected', 'Account Rejected'), ('account_suspended', 'Account Suspended'), ('account_unsuspended', 'Account Unsuspended'), ('account_pending', 'Account Pending Approval'), ('stall_created', 'Stall Created'), ('stall_updated', 'Stall Updated'), ('stall_toggled', 'Stall Toggled'), ('stall_approved', 'Stall Approved'), ('stall_rejected', 'Stall Rejected')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='notificationsnotification',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='orders.ordersorder'),
        ),
        migrations.AddField(
            model_name='notificationsnotification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notificationsnotification',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='notificationsnotification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
