# Generated by Django 5.2.11 on 2026-03-23 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notificationsnotification_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationsnotification',
            name='notification_type',
            field=models.CharField(blank=True, choices=[('order_placed', 'Order Placed'), ('order_confirmed', 'Order Confirmed'), ('order_preparing', 'Order Preparing'), ('order_ready', 'Order Ready'), ('order_picked_up', 'Order Picked Up'), ('order_out_for_delivery', 'Order Out for Delivery'), ('order_completed', 'Order Completed'), ('order_cancelled', 'Order Cancelled'), ('account_approved', 'Account Approved'), ('account_rejected', 'Account Rejected'), ('account_suspended', 'Account Suspended'), ('account_unsuspended', 'Account Unsuspended'), ('account_pending', 'Account Pending Approval'), ('stall_created', 'Stall Created'), ('stall_updated', 'Stall Updated'), ('stall_toggled', 'Stall Toggled'), ('stall_approved', 'Stall Approved'), ('stall_rejected', 'Stall Rejected'), ('stall_created', 'Stall Created'), ('stall_updated', 'Stall Updated'), ('stall_toggled', 'Stall Toggled'), ('stall_approved', 'Stall Approved'), ('stall_rejected', 'Stall Rejected')], max_length=50, null=True),
        ),
    ]
