# Generated by Django 5.2.11 on 2026-03-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_alter_notificationsnotification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationsnotification',
            name='notification_type',
            field=models.CharField(blank=True, choices=[('order_placed', 'Order Placed'), ('order_confirmed', 'Order Confirmed'), ('order_preparing', 'Order Preparing'), ('order_ready', 'Order Ready'), ('order_picked_up', 'Order Picked Up'), ('order_out_for_delivery', 'Order Out for Delivery'), ('order_completed', 'Order Completed'), ('order_cancelled', 'Order Cancelled'), ('account_approved', 'Account Approved'), ('account_rejected', 'Account Rejected'), ('account_suspended', 'Account Suspended'), ('account_unsuspended', 'Account Unsuspended'), ('account_pending', 'Account Pending Approval'), ('stall_created', 'Stall Created'), ('stall_updated', 'Stall Updated'), ('stall_toggled', 'Stall Toggled'), ('stall_approved', 'Stall Approved'), ('stall_rejected', 'Stall Rejected'), ('stall_created', 'Stall Created'), ('stall_updated', 'Stall Updated'), ('stall_toggled', 'Stall Toggled'), ('stall_approved', 'Stall Approved'), ('stall_rejected', 'Stall Rejected'), ('category_created', 'Category Created'), ('category_updated', 'Category Updated'), ('category_deleted', 'Category Deleted'), ('food_item_created', 'Food Item Created'), ('food_item_toggled', 'Food Item Toggled'), ('food_item_updated', 'Food Item Updated')], max_length=50, null=True),
        ),
    ]
