# Generated by Django 5.2.11 on 2026-02-25 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrdersOrder',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.TextField(blank=True, null=True)),
                ('payment_method', models.TextField()),
                ('order_type', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'orders_order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrdersOrderitem',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('price_at_order', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'orders_orderitem',
                'managed': False,
            },
        ),
    ]
