# Generated by Django 5.2.11 on 2026-03-10 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersorder',
            name='cancelled_by',
            field=models.CharField(blank=True, choices=[('customer', 'Customer'), ('vendor', 'Vendor')], max_length=20, null=True),
        ),
    ]
