# Generated by Django 5.2.11 on 2026-03-10 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_ordersorder_cancelled_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersorder',
            name='cancel_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
