# Generated by Django 5.2.11 on 2026-03-18 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_ordersorder_cancel_reason'),
        ('users', '0010_userscustomeraddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersorder',
            name='rider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to='users.usersriderprofile'),
        ),
    ]
