# Generated by Django 5.2.11 on 2026-02-25 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationsVendorrecommendation',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('recommendation_text', models.TextField()),
                ('recommendation_type', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'recommendations_vendorrecommendation',
                'managed': False,
            },
        ),
    ]
