# Generated by Django 5.2.11 on 2026-02-25 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsAigenerationlog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('execution_date', models.DateField()),
                ('customers_generated', models.IntegerField(blank=True, null=True)),
                ('orders_generated', models.IntegerField(blank=True, null=True)),
                ('reviews_generated', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'analytics_aigenerationlog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AnalyticsDailyanalytics',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(unique=True)),
                ('total_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_orders', models.IntegerField(blank=True, null=True)),
                ('new_customers', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'analytics_dailyanalytics',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AnalyticsFoodperformance',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('total_sold', models.IntegerField(blank=True, null=True)),
                ('total_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('average_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
            ],
            options={
                'db_table': 'analytics_foodperformance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AnalyticsVendoranalytics',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('total_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_orders', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'analytics_vendoranalytics',
                'managed': False,
            },
        ),
    ]
