# Generated by Django 5.2.11 on 2026-02-25 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersuser',
            options={'managed': True},
        ),
    ]
