# Generated by Django 5.2.11 on 2026-02-25 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userscustomerprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscustomerprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/customers/'),
        ),
        migrations.AddField(
            model_name='usersvendorprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/vendors/'),
        ),
    ]
