# Generated by Django 5.2.11 on 2026-02-25 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0002_alter_usersuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userscustomerprofile',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='usersvendorprofile',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='usersuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='usersuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='usersuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usersuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
