# Generated by Django 5.2.11 on 2026-02-26 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userscustomerprofile_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='usersuser',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='historicalusersvendorprofile',
            name='is_approved',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='usersvendorprofile',
            name='is_approved',
            field=models.BooleanField(null=True),
        ),
    ]
