# Generated by Django 5.2.11 on 2026-02-28 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_usersuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluserscustomerprofile',
            name='genser',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other'), ('PREFER_NOT', 'Prefer not to say')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalusersvendorprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other'), ('PREFER_NOT', 'Prefer not to say')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userscustomerprofile',
            name='genser',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other'), ('PREFER_NOT', 'Prefer not to say')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usersvendorprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other'), ('PREFER_NOT', 'Prefer not to say')], max_length=20, null=True),
        ),
    ]
