# Generated by Django 5.2.11 on 2026-03-08 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_usersuser_role_historicalusersriderprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalusersriderprofile',
            name='suffix',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usersriderprofile',
            name='suffix',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
