# Generated by Django 5.2.11 on 2026-03-08 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_historicalusersriderprofile_suffix_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersCustomerAddress',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('street', models.CharField(max_length=255)),
                ('barangay', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('province', models.CharField(max_length=255)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='users.userscustomerprofile')),
            ],
            options={
                'db_table': 'users_customeraddress',
                'ordering': ['-is_default', 'created_at'],
            },
        ),
    ]
