# Generated by Django 5.2.11 on 2026-03-19 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_ordersorder_rider'),
        ('users', '0010_userscustomeraddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiderActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('changes', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rider_activity_logs', to='orders.ordersorder')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='users.usersriderprofile')),
            ],
            options={
                'db_table': 'users_rideractivitylog',
                'ordering': ['-timestamp'],
                'managed': True,
            },
        ),
    ]
